name: controller_app
description: "UCP experimental phone-to-Windows input controller."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.13.3

dependencies:
  flutter:
    sdk: flutter
  ucp_core:
    path: ../core

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
